In [2]:
import numpy as np

npz_file_path = "C:/Users/Miko7/Studia/doktorat/FLEX-main/data/data_h36m_keypoints_2d_from_backbone_S1.npz"

data = np.load(npz_file_path, allow_pickle=True)

In [3]:
print(data.files)

['data_2d_backbone']


In [5]:
raw_dict = data['data_2d_backbone']
print(type(raw_dict ))
print(raw_dict.dtype)
print(raw_dict.shape)

<class 'numpy.ndarray'>
object
()


In [6]:
loaded_dict = raw_dict.item()
loaded_dict.keys()

dict_keys(['Directions-1', 'Directions-2', 'Discussion-1', 'Discussion-2', 'Eating-1', 'Eating-2', 'Greeting-1', 'Greeting-2', 'Phoning-1', 'Phoning-2', 'Posing-1', 'Posing-2', 'Purchases-1', 'Purchases-2', 'Sitting-1', 'Sitting-2', 'SittingDown-1', 'SittingDown-2', 'Smoking-1', 'Smoking-2', 'TakingPhoto-1', 'TakingPhoto-2', 'Waiting-1', 'Waiting-2', 'Walking-1', 'Walking-2', 'WalkingDog-1', 'WalkingDog-2', 'WalkingTogether-1', 'WalkingTogether-2'])

In [7]:
loaded_dict['Directions-1'].keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,

In [8]:
loaded_dict['Directions-1'][0].shape

(1, 4, 17, 2)

In [12]:
loaded_dict['Directions-1'][0][0][0]

array([[234.31848 , 348.07742 ],
       [209.10556 , 259.86267 ],
       [230.83617 , 176.53622 ],
       [176.0367  , 175.92574 ],
       [187.40533 , 267.76102 ],
       [199.77835 , 360.21194 ],
       [203.9777  , 176.0404  ],
       [216.31288 , 129.3618  ],
       [211.77182 ,  72.2668  ],
       [215.90323 ,  30.192934],
       [245.08676 , 188.20403 ],
       [249.71107 , 144.00917 ],
       [239.3365  ,  87.60951 ],
       [184.41957 ,  91.92437 ],
       [163.87595 , 147.9566  ],
       [144.49887 , 188.00034 ],
       [208.45741 ,  51.747993]], dtype=float32)

In [16]:
loaded_dict['Directions-1'][43][0][0]

array([[216.05078 , 351.71786 ],
       [208.03575 , 260.30865 ],
       [215.91661 , 171.9424  ],
       [168.55814 , 180.0441  ],
       [175.72346 , 268.12244 ],
       [180.3628  , 360.14612 ],
       [192.10555 , 175.98447 ],
       [199.60901 , 125.15259 ],
       [199.77393 ,  72.09936 ],
       [200.75874 ,  29.081558],
       [248.57793 , 190.90022 ],
       [239.97571 , 141.49255 ],
       [223.85913 ,  87.291214],
       [174.17401 ,  88.03996 ],
       [155.53146 , 144.22926 ],
       [135.93837 , 192.5141  ],
       [195.983   ,  51.974033]], dtype=float32)

In [33]:
loaded_dict['Directions-1'][3][0]

array([[[234.7058  , 348.35025 ],
        [209.66907 , 259.9391  ],
        [228.97504 , 177.6515  ],
        [176.0064  , 175.95132 ],
        [186.9374  , 267.30426 ],
        [199.864   , 360.10495 ],
        [203.74585 , 176.10805 ],
        [216.71992 , 130.47765 ],
        [211.68924 ,  72.39147 ],
        [215.9212  ,  29.805532],
        [244.19386 , 188.02278 ],
        [250.55646 , 144.00117 ],
        [239.03085 ,  87.70108 ],
        [184.32455 ,  91.9753  ],
        [163.88947 , 148.01724 ],
        [144.58496 , 187.95772 ],
        [208.63524 ,  51.753708]],

       [[175.84612 , 339.71472 ],
        [177.05556 , 264.00436 ],
        [184.01582 , 172.11906 ],
        [232.49922 , 171.84395 ],
        [224.17899 , 260.81537 ],
        [216.3282  , 347.74252 ],
        [208.40877 , 171.97963 ],
        [205.34737 , 123.91979 ],
        [211.2259  ,  71.43921 ],
        [207.63364 ,  29.016972],
        [150.42487 , 187.96268 ],
        [164.1211  , 139.78789 ],
        [183

In [18]:
WIDTH, HEIGHT = 960, 540

In [20]:
import numpy as np

width_height_multiplier = np.array([960, 540])

In [21]:
sample_frame = np.array([0.34234, 0.593432])
sample_frame

array([0.34234 , 0.593432])

In [23]:
(width_height_multiplier * sample_frame).astype(int)

array([328, 320])

In [40]:
sample_frame = np.array([[[0.34234, 0.593432],
                         [0.56344, 0.677783],
                         [0.53423, 0.333333],
                         [1, 1]],
                         [[0.34234, 0.593432],
                         [0.56344, 0.677783],
                         [0.53423, 0.333333],
                         [0, 0]],
                         [[0.34234, 0.593432],
                         [0.56344, 0.677783],
                         [0.53423, 0.333333],
                         [0.5, 0.5]]
                        ])

In [42]:
r = (width_height_multiplier * sample_frame).astype(int)
r

array([[[328, 320],
        [540, 366],
        [512, 179],
        [960, 540]],

       [[328, 320],
        [540, 366],
        [512, 179],
        [  0,   0]],

       [[328, 320],
        [540, 366],
        [512, 179],
        [480, 270]]])

In [43]:
r.shape

(3, 4, 2)

In [46]:
import json

with open("./datasets/yolo/dataset_v2.json", "r") as file:
    yolo_output = json.load(file)


In [48]:
yolo_output.keys()

dict_keys(['p1s1', 'p1s2', 'p1s3', 'p1s4', 'p2s1', 'p2s2', 'p2s3', 'p2s4', 'p3s1', 'p3s2', 'p3s3', 'p3s4', 'p4s1', 'p4s2', 'p4s3', 'p4s4', 'p5s1', 'p5s2', 'p5s3', 'p5s4', 'p6s1', 'p6s2', 'p6s3', 'p6s4', 'p7s1', 'p7s2', 'p7s3', 'p7s4', 'p8s1', 'p8s2', 'p8s3', 'p8s4', 'p9s1', 'p9s2', 'p9s3', 'p9s4', 'p10s1', 'p10s2', 'p10s3', 'p10s4', 'p11s1', 'p11s2', 'p11s3', 'p11s4', 'p12s1', 'p12s2', 'p12s3', 'p12s4', 'p13s1', 'p13s2', 'p13s3', 'p13s4', 'p14s1', 'p14s2', 'p14s3', 'p14s4', 'p15s1', 'p15s2', 'p15s3', 'p15s4', 'p16s1', 'p16s2', 'p16s3', 'p16s4', 'p17s1', 'p17s2', 'p17s3', 'p17s4', 'p18s1', 'p18s2', 'p18s3', 'p18s4', 'p19s1', 'p19s2', 'p19s3', 'p19s4', 'p20s1', 'p20s2', 'p20s3', 'p20s4', 'p21s1', 'p21s2', 'p21s3', 'p21s4', 'p22s1', 'p22s2', 'p22s3', 'p22s4', 'p23s1', 'p23s2', 'p23s3', 'p23s4', 'p24s1', 'p24s2', 'p24s3', 'p24s4', 'p25s1', 'p25s2', 'p25s3', 'p25s4', 'p26s1', 'p26s2', 'p26s3', 'p26s4', 'p26s5', 'p26s6', 'p26s7', 'p26s8', 'p27s1', 'p27s2', 'p27s3', 'p27s4', 'p27s5', 'p27s6',

In [61]:
frame = np.array(yolo_output['p1s1']['c1']['23'])
frame

array([[0.81468254, 0.25607488],
       [0.82066023, 0.24663535],
       [0.81366861, 0.24564576],
       [0.83701009, 0.25031886],
       [0.        , 0.        ],
       [0.85054147, 0.30710089],
       [0.81939971, 0.3050184 ],
       [0.85788578, 0.38989741],
       [0.        , 0.        ],
       [0.85471869, 0.45867491],
       [0.        , 0.        ],
       [0.83622384, 0.4475112 ],
       [0.8210597 , 0.44273657],
       [0.80668861, 0.54128438],
       [0.82871348, 0.54360926],
       [0.80001491, 0.65552074],
       [0.87178367, 0.6063022 ]])

In [62]:
(width_height_multiplier * frame)

array([[782.09524155, 138.28043282],
       [787.83382416, 133.18308771],
       [781.12186432, 132.6487112 ],
       [803.52968216, 135.17218173],
       [  0.        ,   0.        ],
       [816.51981354, 165.83448172],
       [786.62372589, 164.7099334 ],
       [823.57034683, 210.54459929],
       [  0.        ,   0.        ],
       [820.52993774, 247.68445015],
       [  0.        ,   0.        ],
       [802.77488708, 241.65604591],
       [788.21731567, 239.07774568],
       [774.42106247, 292.29356647],
       [795.56493759, 293.54900122],
       [768.01431656, 353.98119807],
       [836.91232681, 327.40318894]])

In [88]:
result = {}

for sequence_key, sequence_data in yolo_output.items():
    print(sequence_key, end=' | ')
    sequence_result = [[] for _ in range(len(sequence_data['c1'].keys()))]
    for c_idx in range(1, 5):
        camera = f"c{c_idx}"
        for f_idx, frame in sequence_data[camera].items():
            frame_scaled = width_height_multiplier * np.array(frame)
            if int(f_idx) < len(sequence_result): # p30s8 error?
                sequence_result[int(f_idx)].append(frame_scaled)

    result[sequence_key] = {i: np.array([combined_frame_result]) for i, combined_frame_result in enumerate(sequence_result)}
    

p1s1 | p1s2 | p1s3 | p1s4 | p2s1 | p2s2 | p2s3 | p2s4 | p3s1 | p3s2 | p3s3 | p3s4 | p4s1 | p4s2 | p4s3 | p4s4 | p5s1 | p5s2 | p5s3 | p5s4 | p6s1 | p6s2 | p6s3 | p6s4 | p7s1 | p7s2 | p7s3 | p7s4 | p8s1 | p8s2 | p8s3 | p8s4 | p9s1 | p9s2 | p9s3 | p9s4 | p10s1 | p10s2 | p10s3 | p10s4 | p11s1 | p11s2 | p11s3 | p11s4 | p12s1 | p12s2 | p12s3 | p12s4 | p13s1 | p13s2 | p13s3 | p13s4 | p14s1 | p14s2 | p14s3 | p14s4 | p15s1 | p15s2 | p15s3 | p15s4 | p16s1 | p16s2 | p16s3 | p16s4 | p17s1 | p17s2 | p17s3 | p17s4 | p18s1 | p18s2 | p18s3 | p18s4 | p19s1 | p19s2 | p19s3 | p19s4 | p20s1 | p20s2 | p20s3 | p20s4 | p21s1 | p21s2 | p21s3 | p21s4 | p22s1 | p22s2 | p22s3 | p22s4 | p23s1 | p23s2 | p23s3 | p23s4 | p24s1 | p24s2 | p24s3 | p24s4 | p25s1 | p25s2 | p25s3 | p25s4 | p26s1 | p26s2 | p26s3 | p26s4 | p26s5 | p26s6 | p26s7 | p26s8 | p27s1 | p27s2 | p27s3 | p27s4 | p27s5 | p27s6 | p27s7 | p27s8 | p28s1 | p28s2 | p28s3 | p28s4 | p28s5 | p28s6 | p28s7 | p28s8 | p29s1 | p29s2 | p29s3 | p29s4 | p29s5 | p29s

In [75]:
sequence_result_dict.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134])

In [72]:
loaded_dict['Directions-1'][0].shape

(1, 4, 17, 2)

In [90]:
result['p7s1'][0].shape

(1, 4, 17, 2)

In [101]:
to_save = {'data_2d_backbone': result}

In [119]:
# np.savez("./datasets/yolo/gpjatk.npz", **to_save)
np.savez("./datasets/yolo/gpjatk.npz", data_2d_backbone=np.array(result, dtype=object))

In [120]:
results_npz = np.load("./datasets/yolo/gpjatk.npz", allow_pickle=True)

In [134]:
results_npz['data_2d_backbone'].item()['p1s1'].keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134])